#!/bin/bash

# Put this config file at same directory level that your slides
CONFIG_FILE=builder.conf; [ -f $CONFIG_FILE ] && source $CONFIG_FILE

# Default values (configurable in builder.conf, for example)
RESOURCES=${RESOURCES:-"reveal.js images"}
DEFAULT_OP=${DEFAULT_OP:-html}
NEEDED_GEMS=${NEEDED_GEMS:-'asciidoctor tilt thread_safe slim'}
BUILDER_PREPARED=${BUILDER_PREPARED:-'builder.prepared'}

####################
# Auxiliar functions
####################

# Install Asciidoctor and necessary dependencies
gem_install_asciidoctor_and_dependencies() {
    local gem
    for gem in $NEEDED_GEMS
    do
        gem list $gem |
        if ! grep -q "$gem "
        then
            if ! gem install $gem
            then
                echo "gem install $gem fails :("
                case "$OSTYPE" in
                    darwin*)
                        echo "trying to install with sudo ..."
                        # http://stackoverflow.com/a/32892222
                        sudo gem install -n /usr/local/bin $gem
                        ;;
                esac
            fi
        fi
    done
}

# Clone the necessary projects
git_clone_projects() {
    if ! [ -d asciidoctor-reveal.js/.git ]
    then
        git clone https://github.com/asciidoctor/asciidoctor-reveal.js
    fi

    if ! [ -d reveal.js/.git ]
    then
        git clone -b 3.0.0 https://github.com/hakimel/reveal.js
    fi
}

# Main function
main() {
    local op=$1

    [ "$op" ] || op=$DEFAULT_OP
    while [ "$op" ]
    do
        shift
        if ! type _$op &> /dev/null
        then
            echo "Target \"$op\" does'nt exists!"
        else
            _$op "$@"
        fi
        op=$1
    done
}

#########
# Targets
#########

# Prepare the environment to build presentations
_prepare() {
    gem_install_asciidoctor_and_dependencies
    git_clone_projects
    touch "$BUILDER_PREPARED"
}

# Build HTML. Verify if asciidoctor and dependencies are installed. If not, install it.
_html() {
    [ -f "$BUILDER_PREPARED" ] || _prepare
    local adoc
    for adoc in `find . -maxdepth 1 -type f -name '*.adoc'`
    do
        adoc=`basename $adoc`
        local html=${adoc%.*}
        if [ $adoc -nt $html ]
        then
            asciidoctor -a revealjs -T asciidoctor-reveal.js/templates/slim $adoc
        fi
    done
}

# Create a zip with all necessary resources to distribute 
_dist() {
    local zip_dir=`basename $PWD`
    local zip_resources
    
    local res
    for res in $RESOURCES
    do
        zip_resources="$zip_dir/$res $zip_resources"
    done

    cd ..
    zip -r $zip_dir.zip $zip_dir/*.html $zip_resources
    cd -> /dev/null
}

# Remove HTML.
_clean() {
    rm -f *.html
}

# Remove HTML and downloaded files.
_clean_all() {
    _clean
    rm -rf asciidoctor-reveal.js reveal.js "$BUILDER_PREPARED"
}

#############
# Start point
#############

main "$@"
