#!/bin/bash
set +x

export DEFAULT_OP=${1:-dzslides}
export BASEDIR=`cd "$(dirname "$0")"; pwd`
export BUILD_DIR=${BUILD_DIR:-target}/dzslides

[ "$1" ] && shift
"`dirname "$BASEDIR"`"/build $DEFAULT_OP "$@"
